#-------------------------------------------------------------
# Basic configuration settings for the plugin.
# Основные настройки конфигурации плагина.
#-------------------------------------------------------------
wg_region_protect:
  #-------------------------------------------------------------
  # List of protected regions.
  # If regions are not needed, specify an empty parameter:
  # region_protect: []
  #-------------------------------------------------------------
  # Список защищенных регионов.
  # Если регионы не нужны, укажите пустой параметр:
  # region_protect: []
  #-------------------------------------------------------------
  region_protect:
    - spawn
    - pvp

  #--------------------------------------------------------------------------------------
  # List of protected regions where breaking is allowed.
  # If regions are not needed, specify an empty parameter:
  # region_protect_allow: []
  #--------------------------------------------------------------------------------------
  # Список защищенных регионов в которых разрешено ломать.
  # Если регионы не нужны, укажите пустой параметр:
  # region_protect_allow: []
  region_protect_allow: []

  #--------------------------------------------------------------------------------------
  # List of protected regions where only breaking is allowed.
  # If regions are not needed, specify an empty parameter:
  # region_protect_only_break_allow: []
  #-------------------------------------------------------------
  # Список защищенных регионов в которых разрешено только ломать.
  # Если регионы не нужны, укажите пустой параметр:
  # region_protect_only_break_allow: []
  #--------------------------------------------------------------------------------------
  region_protect_only_break_allow: []

  # --------------------------------------------------------------------------------------
  # List of prohibited entity / block for interaction in the protected region.
  # If you don't want to block it, specify an empty parameter:
  #
  # Attention! In interact_type, the block IDs\items are different from Minecraft!
  # list of blocks prohibited by default\items:
  # - armor_stand
  # - end_crystal
  # - minecart
  # - tnt_minecart
  # - command_block_minecart
  # - hopper_minecart
  # - chest_minecart
  # - furnace_minecart
  # - oak_boat
  # - acacia_boat
  # - spruce_boat
  # - birch_boat
  # - jungle_boat
  # - jungle_boat
  # - dark_oak_boat
  # - bucket
  # - water_bucket
  # - lava_bucket
  #
  # interact_type: []
  # --------------------------------------------------------------------------------------
  # Список запрещенных entity/block для взаимодействия в защищенном регионе.
  # Если не нужно блокировать, то укажите пустой параметр:
  # interact_type: []
  # --------------------------------------------------------------------------------------
  interact_type:
    - armor_stand
    - end_crystal
    - minecart
    - tnt_minecart
    - command_block_minecart
    - hopper_minecart
    - chest_minecart
    - furnace_minecart
    - oak_boat
    - acacia_boat
    - spruce_boat
    - birch_boat
    - jungle_boat
    - jungle_boat
    - dark_oak_boat
    - bucket
    - water_bucket
    - lava_bucket

  #--------------------------------------------------------------------------------------
  # List of forbidden commands from WE / FAWE.
  # Список запрещенных команд от WE / FAWE.
  #--------------------------------------------------------------------------------------
  no_protect_cmd:
    command_we:
    - //set
    - //replace
    - //overlay
    - //walls
    - //deform
    - //fill
    - //fillr
    - //fixlava
    - //hollow
    - //move
    - //stack
    - //smooth
    - //cut
    - //replacenear
    command_c:
    - //cyl
    - //hcyl
    - //drain
    - //rep
    command_p:
    - //pyramid
    - //hpyramid
    command_s:
    - //sphere
    - //hsphere
    command_u:
    - //up
    - /up
    command_cp:
    - //paste
    - //place
    - //replacenear
    - //hollow

  #--------------------------------------------------------------------------------------
  # Turn Enable/Disable the exploding from Entity(tnt, creeper and etc.).
  # Включить/Выключить эффект взрыва от энтити(динамит, крипер и подобных).
  #--------------------------------------------------------------------------------------
  explodeEntity:
    enable: true

  #--------------------------------------------------------------------------------------
  # Turn Enable/Disable the notification if player try to use in the protected region WE\FAWE command.
  # Включить/Выключить оповещение в консоль и админу если игрок попытался использовать команду в защищенном регионе.
  #--------------------------------------------------------------------------------------
  spy_command:
    notify:
      # Enable notify of action for admin and console.
      # Включение оповещения в консоль и администратору.
      console:
        enable: true
      admin:
        enable: true
      # Settings of sound for admin.
      # Звуковое оповещение администратора.
      sound:
        enable: true
        # All sounds can be found here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
        # Все звуки из 1.18.2 могут быть найдены тут: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
        type: BLOCK_ANVIL_PLACE
    # A list of commands that will be tracked in the /wgrp spy command
    # Список команд которые будут отслеживаться в команде /wgrp spy
    spy_command_list:
      - //set
      - //replace
      - //overlay
      - //walls
      - //deform
      - //fill
      - //fillr
      - //fixlava
      - //hollow
      - //move
      - //stack
      - //smooth
      - //cut
      - //replacenear

  #--------------------------------------------------------------------------------------
  # Turn Enable/Disable the protected region message.
  # Включить/Выключить сообщение о защищенном регионе.
  #--------------------------------------------------------------------------------------
  protect_message: true
  #--------------------------------------------------------------------------------------
  # Turn Enable/Disable the protected region message when using the WE\FAWE commands.
  # Включить/Выключить сообщение о защищенном регионе при использовании команд WE\FAWE.
  #--------------------------------------------------------------------------------------
  protect_we_message: true

  dataSource:
    enable: false
    database: wgrp_core
    host: localhost
    port: 3306
    user: root
    password: root
    table: wgrp_logs
    useSsl: true

    #--------------------------------------------------------------------------------------
    # Pool settings...
    #--------------------------------------------------------------------------------------
    maxPoolSize: 10
    maxLifetime: 1800
    connectionTimeout: 5000
    intervalReload: 60