[versions]
shadow = "9.2.2"
blossom = "1.3.1"
loom = "1.6-SNAPSHOT"
runPaper = "2.3.1"

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
blossom = { id = "net.kyori.blossom", version.ref = "blossom" }
loom = { id = "fabric-loom", version.ref = "loom" }
runPaper = { id = "xyz.jpenilla.run-paper", version.ref = "runPaper" }