[versions]
shadow = "8.1.7"
blossom = "1.3.1"
loom = "1.6-SNAPSHOT"
runPaper = "2.3.1"

# Provided
paperDev = "1.7.0"
paper = "1.21.1-R0.1-SNAPSHOT"

[plugins]
shadow = { id = "io.github.goooler.shadow", version.ref = "shadow" }
blossom = { id = "net.kyori.blossom", version.ref = "blossom" }
loom = { id = "fabric-loom", version.ref = "loom" }
runPaper = { id = "xyz.jpenilla.run-paper", version.ref = "runPaper" }
paperDev = { id = "io.papermc.paperweight.userdev", version.ref = "paperDev" }

[libraries]
paper = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper" }
